name: 'PR Preview Multi Tenant'
description: 'Preview websites with multi options'
author: 'gbernini'
inputs:
  surge_token:
    description: 'surge.sh token'
    required: true
  preview_url:
    description: 'string with repo options'
    default: '{{repoOwner}}-{{repoName}}-{{job}}-pr-{{prNumber}}'
    required: false
  preview_path:
    description: 'direct route for preview url'
    default: ''
    required: false
  github_token:
    description: 'github token'
    required: true
  build:
    description: 'build scripts'
    default: |
      npm install
      npm run build
    required: false
  dist:
    description: 'dist folder to deploy'
    default: 'public'
    required: false
  failOnError:
    description: 'Set `failed` if a deployment throws error'
  teardown:
    description: 'Determines if the preview instance will be torn down on PR close'
    default: 'false'
    required: false
  vercel_token:
    description: 'Vercel token'
    required: false
outputs:
  preview_url:
    description: 'The url for the related PR preview'
runs:
  using: node16
  main: 'dist/index.js'
branding:
  icon: 'monitor'
  color: 'yellow'
